CREATE TABLE CURRENCY_EXCHANGE (
    ID BIGINT NOT NULL,
    CONVERSION_MULTIPLE NUMERIC(38,2), -- Use NUMERIC or DECIMAL for BigDecimal
    CURRENCY_FROM VARCHAR(255),
    CURRENCY_TO VARCHAR(255),
    ENVIRONEMENT VARCHAR(255),         -- Matches your entity's 'environement'
    PRIMARY KEY (ID)
);